CREATE TABLE IF NOT EXISTS recetas (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL UNIQUE,
  descripcion TEXT,
  tiempo INT,
  dificultad VARCHAR(50),
  costo_estimado NUMERIC(10,2)
);
CREATE TABLE IF NOT EXISTS receta_ingredientes (
  id SERIAL PRIMARY KEY,
  receta_id INT REFERENCES recetas(id),
  ingrediente VARCHAR(100) NOT NULL,
  cantidad NUMERIC(10,2),
  unidad VARCHAR(20),
  obligatorio BOOLEAN DEFAULT true,
  UNIQUE(receta_id, ingrediente)
);
CREATE INDEX IF NOT EXISTS idx_recetas_nombre ON recetas(nombre);
CREATE INDEX IF NOT EXISTS idx_receta_ingrediente ON receta_ingredientes(ingrediente);
CREATE INDEX IF NOT EXISTS idx_receta_ingrediente_lower ON receta_ingredientes(lower(ingrediente));

INSERT INTO recetas(nombre, descripcion, tiempo, dificultad, costo_estimado) VALUES
('Arroz con pollo rápido', 'Receta económica usando arroz y pollo.', 30, 'facil', 4.50),
('Ensalada de atún', 'Receta fría y rápida con atún y vegetales.', 15, 'facil', 3.50),
('Tortilla de papa', 'Plato casero con papa y huevo.', 25, 'media', 2.80),
('Pasta al pomodoro', 'Pasta con salsa de tomate fresco y albahaca.', 20, 'facil', 3.20),
('Sopa de verduras', 'Caldo reconfortante con zanahoria, papa y apio.', 35, 'facil', 2.50),
('Tortilla española', 'Clásico ibérico de papa y huevo.', 25, 'media', 2.80),
('Pollo al curry', 'Pechugas en salsa de curry con leche de coco.', 40, 'media', 5.50),
('Crema de brócoli', 'Sopa crema suave con brócoli y queso.', 30, 'facil', 3.00),
('Lomo saltado', 'Salteado latino de carne, tomate y papa frita.', 25, 'media', 6.50),
('Bowl vegetariano de arroz', 'Arroz con vegetales frescos para una comida ligera.', 22, 'facil', 3.20),
('Shakshuka casera', 'Huevos en salsa de tomate, cebolla y ajo.', 24, 'media', 3.60),
('Papas doradas con queso', 'Papas crujientes con queso y cebolla.', 32, 'facil', 2.90),
('Arroz salteado con huevo', 'Arroz rápido con huevo, zanahoria y cebolla.', 18, 'facil', 2.70),
('Pasta con brócoli', 'Pasta ligera con brócoli y ajo.', 23, 'facil', 3.30),
('Tomates rellenos de arroz', 'Tomates horneados con arroz y cebolla.', 38, 'media', 3.10),
('Ensalada tibia de papa', 'Papa, huevo y zanahoria en ensalada casera.', 26, 'facil', 3.00),
('Pollo con papas al horno', 'Bandeja familiar de pollo, papa y zanahoria.', 50, 'media', 5.80),
('Sopa de tomate', 'Sopa suave con tomate, cebolla y ajo.', 25, 'facil', 2.40),
('Arepitas de queso', 'Bocados rápidos de queso y huevo.', 20, 'facil', 3.80),
('Curry vegetal', 'Verduras con arroz y especias suaves.', 35, 'media', 4.20),
('Frittata de verduras', 'Huevos al horno con tomate, brócoli y cebolla.', 30, 'facil', 3.50)
ON CONFLICT(nombre) DO NOTHING;

INSERT INTO receta_ingredientes(receta_id, ingrediente, cantidad, unidad, obligatorio)
SELECT r.id, v.ingrediente, v.cantidad, v.unidad, v.obligatorio
FROM (VALUES
('Arroz con pollo rápido','arroz',1,'taza',true),
('Arroz con pollo rápido','pollo',300,'g',true),
('Arroz con pollo rápido','cebolla',1,'unidad',false),
('Ensalada de atún','atun',1,'lata',true),
('Ensalada de atún','lechuga',1,'unidad',false),
('Ensalada de atún','tomate',1,'unidad',false),
('Tortilla de papa','papa',3,'unidad',true),
('Tortilla de papa','huevo',2,'unidad',true),
('Pasta al pomodoro','pasta',200,'g',true),
('Pasta al pomodoro','tomate',3,'unidad',true),
('Pasta al pomodoro','ajo',2,'unidad',false),
('Sopa de verduras','zanahoria',2,'unidad',true),
('Sopa de verduras','papa',2,'unidad',true),
('Sopa de verduras','apio',1,'tallo',false),
('Tortilla española','papa',3,'unidad',true),
('Tortilla española','huevo',3,'unidad',true),
('Tortilla española','cebolla',1,'unidad',false),
('Pollo al curry','pollo',300,'g',true),
('Pollo al curry','cebolla',1,'unidad',true),
('Pollo al curry','ajo',3,'unidad',false),
('Crema de brócoli','brocoli',2,'unidad',true),
('Crema de brócoli','queso',50,'g',false),
('Lomo saltado','carne',300,'g',true),
('Lomo saltado','papa',2,'unidad',true),
('Lomo saltado','tomate',2,'unidad',true),
('Bowl vegetariano de arroz','arroz',1,'taza',true),
('Bowl vegetariano de arroz','brocoli',1,'unidad',true),
('Bowl vegetariano de arroz','zanahoria',1,'unidad',false),
('Bowl vegetariano de arroz','tomate',1,'unidad',false),
('Shakshuka casera','huevo',2,'unidad',true),
('Shakshuka casera','tomate',3,'unidad',true),
('Shakshuka casera','cebolla',1,'unidad',false),
('Papas doradas con queso','papa',3,'unidad',true),
('Papas doradas con queso','queso',80,'g',true),
('Papas doradas con queso','cebolla',1,'unidad',false),
('Arroz salteado con huevo','arroz',1,'taza',true),
('Arroz salteado con huevo','huevo',2,'unidad',true),
('Arroz salteado con huevo','zanahoria',1,'unidad',false),
('Pasta con brócoli','pasta',200,'g',true),
('Pasta con brócoli','brocoli',1,'unidad',true),
('Pasta con brócoli','ajo',2,'unidad',false),
('Tomates rellenos de arroz','tomate',4,'unidad',true),
('Tomates rellenos de arroz','arroz',1,'taza',true),
('Tomates rellenos de arroz','cebolla',1,'unidad',false),
('Ensalada tibia de papa','papa',2,'unidad',true),
('Ensalada tibia de papa','huevo',2,'unidad',true),
('Ensalada tibia de papa','zanahoria',1,'unidad',false),
('Pollo con papas al horno','pollo',300,'g',true),
('Pollo con papas al horno','papa',3,'unidad',true),
('Pollo con papas al horno','zanahoria',1,'unidad',false),
('Sopa de tomate','tomate',4,'unidad',true),
('Sopa de tomate','cebolla',1,'unidad',true),
('Sopa de tomate','ajo',2,'unidad',false),
('Arepitas de queso','queso',120,'g',true),
('Arepitas de queso','huevo',1,'unidad',true),
('Curry vegetal','arroz',1,'taza',true),
('Curry vegetal','brocoli',1,'unidad',true),
('Curry vegetal','zanahoria',1,'unidad',true),
('Curry vegetal','cebolla',1,'unidad',false),
('Frittata de verduras','huevo',3,'unidad',true),
('Frittata de verduras','tomate',1,'unidad',false),
('Frittata de verduras','brocoli',1,'unidad',false),
('Frittata de verduras','cebolla',1,'unidad',false)
) AS v(receta_nombre, ingrediente, cantidad, unidad, obligatorio)
JOIN recetas r ON r.nombre = v.receta_nombre
ON CONFLICT(receta_id, ingrediente) DO NOTHING;
