CREATE TABLE IF NOT EXISTS recetas (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL UNIQUE,
  descripcion TEXT,
  tiempo INT,
  dificultad VARCHAR(50),
  costo_estimado NUMERIC(10,2)
);
CREATE TABLE IF NOT EXISTS receta_ingredientes (
  id SERIAL PRIMARY KEY,
  receta_id INT REFERENCES recetas(id),
  ingrediente VARCHAR(100) NOT NULL,
  cantidad NUMERIC(10,2),
  unidad VARCHAR(20),
  obligatorio BOOLEAN DEFAULT true,
  UNIQUE(receta_id, ingrediente)
);
CREATE INDEX IF NOT EXISTS idx_recetas_nombre ON recetas(nombre);
CREATE INDEX IF NOT EXISTS idx_receta_ingrediente ON receta_ingredientes(ingrediente);
CREATE INDEX IF NOT EXISTS idx_receta_ingrediente_lower ON receta_ingredientes(lower(ingrediente));

INSERT INTO recetas(nombre, descripcion, tiempo, dificultad, costo_estimado) VALUES
('Arroz con pollo rápido', 'Receta económica usando arroz y pollo.', 30, 'facil', 4.50),
('Ensalada de atún', 'Receta fría y rápida con atún y vegetales.', 15, 'facil', 3.50),
('Tortilla de papa', 'Plato casero con papa y huevo.', 25, 'media', 2.80),
('Pasta al pomodoro', 'Pasta con salsa de tomate fresco y albahaca.', 20, 'facil', 3.20),
('Sopa de verduras', 'Caldo reconfortante con zanahoria, papa y apio.', 35, 'facil', 2.50),
('Tortilla española', 'Clásico ibérico de papa y huevo.', 25, 'media', 2.80),
('Pollo al curry', 'Pechugas en salsa de curry con leche de coco.', 40, 'media', 5.50),
('Crema de brócoli', 'Sopa crema suave con brócoli y queso.', 30, 'facil', 3.00),
('Lomo saltado', 'Salteado latino de carne, tomate y papa frita.', 25, 'media', 6.50),
('Bowl vegetariano de arroz', 'Arroz con vegetales frescos para una comida ligera.', 22, 'facil', 3.20),
('Shakshuka casera', 'Huevos en salsa de tomate, cebolla y ajo.', 24, 'media', 3.60),
('Papas doradas con queso', 'Papas crujientes con queso y cebolla.', 32, 'facil', 2.90),
('Arroz salteado con huevo', 'Arroz rápido con huevo, zanahoria y cebolla.', 18, 'facil', 2.70),
('Pasta con brócoli', 'Pasta ligera con brócoli y ajo.', 23, 'facil', 3.30),
('Tomates rellenos de arroz', 'Tomates horneados con arroz y cebolla.', 38, 'media', 3.10),
('Ensalada tibia de papa', 'Papa, huevo y zanahoria en ensalada casera.', 26, 'facil', 3.00),
('Pollo con papas al horno', 'Bandeja familiar de pollo, papa y zanahoria.', 50, 'media', 5.80),
('Sopa de tomate', 'Sopa suave con tomate, cebolla y ajo.', 25, 'facil', 2.40),
('Arepitas de queso', 'Bocados rápidos de queso y huevo.', 20, 'facil', 3.80),
('Curry vegetal', 'Verduras con arroz y especias suaves.', 35, 'media', 4.20),
('Frittata de verduras', 'Huevos al horno con tomate, brócoli y cebolla.', 30, 'facil', 3.50),
('Bowl de quinua y verduras', 'Quinua con tomate, zanahoria y brocoli para una comida fresca.', 28, 'facil', 4.10),
('Lentejas guisadas', 'Guiso nutritivo con lentejas, zanahoria y cebolla.', 40, 'facil', 2.90),
('Wrap de pollo y verduras', 'Tortilla suave con pollo, tomate y vegetales crujientes.', 18, 'facil', 4.80),
('Ensalada de garbanzos', 'Garbanzos con tomate, pepino y cebolla en version fresca.', 15, 'facil', 3.20),
('Omelette de espinaca', 'Huevos suaves con espinaca y tomate.', 14, 'facil', 2.70),
('Pasta primavera', 'Pasta con zanahoria, brocoli y tomate.', 26, 'facil', 3.90),
('Arroz con lentejas', 'Arroz rendidor con lentejas y cebolla dorada.', 32, 'facil', 2.60),
('Tacos de frijol y tomate', 'Tacos caseros con frijol, tomate y cebolla.', 20, 'facil', 3.40),
('Pollo con arroz y zanahoria', 'Plato casero suave para aprovechar arroz y pollo.', 35, 'facil', 4.60),
('Sopa de lentejas', 'Sopa caliente, nutritiva y economica.', 38, 'facil', 2.80),
('Ensalada de pasta fria', 'Pasta fria con tomate, zanahoria y atun.', 16, 'facil', 3.80),
('Calabacin salteado con arroz', 'Arroz con calabacin y cebolla salteada.', 22, 'facil', 3.10),
('Pescado al tomate', 'Filete de pescado con tomate y cebolla.', 24, 'media', 5.40),
('Crepes de verduras', 'Crepes suaves rellenos con verduras salteadas.', 34, 'media', 4.00),
('Garbanzos al curry', 'Garbanzos especiados con arroz y verduras.', 30, 'facil', 3.70),
('Bowl de atun y arroz', 'Arroz con atun, tomate y zanahoria.', 15, 'facil', 3.90),
('Sopa minestrone simple', 'Sopa de pasta pequena con verduras y frijoles.', 36, 'facil', 3.30),
('Avena salada con huevo', 'Avena cremosa salada con huevo y tomate.', 12, 'facil', 2.20),
('Papas rellenas de verduras', 'Papas horneadas con brocoli, zanahoria y cebolla.', 42, 'media', 3.60),
('Arroz mediterraneo', 'Arroz con tomate, garbanzo y verduras frescas.', 27, 'facil', 3.50),
('Pollo a la plancha con ensalada', 'Pollo sencillo con tomate, lechuga y zanahoria.', 22, 'facil', 5.00),
('Salteado de verduras con huevo', 'Verduras salteadas con huevo para una cena rapida.', 17, 'facil', 2.90)
ON CONFLICT(nombre) DO NOTHING;

INSERT INTO receta_ingredientes(receta_id, ingrediente, cantidad, unidad, obligatorio)
SELECT r.id, v.ingrediente, v.cantidad, v.unidad, v.obligatorio
FROM (VALUES
('Arroz con pollo rápido','arroz',1,'taza',true),
('Arroz con pollo rápido','pollo',300,'g',true),
('Arroz con pollo rápido','cebolla',1,'unidad',false),
('Ensalada de atún','atun',1,'lata',true),
('Ensalada de atún','lechuga',1,'unidad',false),
('Ensalada de atún','tomate',1,'unidad',false),
('Tortilla de papa','papa',3,'unidad',true),
('Tortilla de papa','huevo',2,'unidad',true),
('Pasta al pomodoro','pasta',200,'g',true),
('Pasta al pomodoro','tomate',3,'unidad',true),
('Pasta al pomodoro','ajo',2,'unidad',false),
('Sopa de verduras','zanahoria',2,'unidad',true),
('Sopa de verduras','papa',2,'unidad',true),
('Sopa de verduras','apio',1,'tallo',false),
('Tortilla española','papa',3,'unidad',true),
('Tortilla española','huevo',3,'unidad',true),
('Tortilla española','cebolla',1,'unidad',false),
('Pollo al curry','pollo',300,'g',true),
('Pollo al curry','cebolla',1,'unidad',true),
('Pollo al curry','ajo',3,'unidad',false),
('Crema de brócoli','brocoli',2,'unidad',true),
('Crema de brócoli','queso',50,'g',false),
('Lomo saltado','carne',300,'g',true),
('Lomo saltado','papa',2,'unidad',true),
('Lomo saltado','tomate',2,'unidad',true),
('Bowl vegetariano de arroz','arroz',1,'taza',true),
('Bowl vegetariano de arroz','brocoli',1,'unidad',true),
('Bowl vegetariano de arroz','zanahoria',1,'unidad',false),
('Bowl vegetariano de arroz','tomate',1,'unidad',false),
('Shakshuka casera','huevo',2,'unidad',true),
('Shakshuka casera','tomate',3,'unidad',true),
('Shakshuka casera','cebolla',1,'unidad',false),
('Papas doradas con queso','papa',3,'unidad',true),
('Papas doradas con queso','queso',80,'g',true),
('Papas doradas con queso','cebolla',1,'unidad',false),
('Arroz salteado con huevo','arroz',1,'taza',true),
('Arroz salteado con huevo','huevo',2,'unidad',true),
('Arroz salteado con huevo','zanahoria',1,'unidad',false),
('Pasta con brócoli','pasta',200,'g',true),
('Pasta con brócoli','brocoli',1,'unidad',true),
('Pasta con brócoli','ajo',2,'unidad',false),
('Tomates rellenos de arroz','tomate',4,'unidad',true),
('Tomates rellenos de arroz','arroz',1,'taza',true),
('Tomates rellenos de arroz','cebolla',1,'unidad',false),
('Ensalada tibia de papa','papa',2,'unidad',true),
('Ensalada tibia de papa','huevo',2,'unidad',true),
('Ensalada tibia de papa','zanahoria',1,'unidad',false),
('Pollo con papas al horno','pollo',300,'g',true),
('Pollo con papas al horno','papa',3,'unidad',true),
('Pollo con papas al horno','zanahoria',1,'unidad',false),
('Sopa de tomate','tomate',4,'unidad',true),
('Sopa de tomate','cebolla',1,'unidad',true),
('Sopa de tomate','ajo',2,'unidad',false),
('Arepitas de queso','queso',120,'g',true),
('Arepitas de queso','huevo',1,'unidad',true),
('Curry vegetal','arroz',1,'taza',true),
('Curry vegetal','brocoli',1,'unidad',true),
('Curry vegetal','zanahoria',1,'unidad',true),
('Curry vegetal','cebolla',1,'unidad',false),
('Frittata de verduras','huevo',3,'unidad',true),
('Frittata de verduras','tomate',1,'unidad',false),
('Frittata de verduras','brocoli',1,'unidad',false),
('Frittata de verduras','cebolla',1,'unidad',false),
('Bowl de quinua y verduras','quinua',1,'taza',true),
('Bowl de quinua y verduras','tomate',1,'unidad',true),
('Bowl de quinua y verduras','zanahoria',1,'unidad',false),
('Bowl de quinua y verduras','brocoli',1,'unidad',false),
('Lentejas guisadas','lenteja',1,'taza',true),
('Lentejas guisadas','zanahoria',1,'unidad',false),
('Lentejas guisadas','cebolla',1,'unidad',false),
('Lentejas guisadas','tomate',1,'unidad',false),
('Wrap de pollo y verduras','pollo',180,'g',true),
('Wrap de pollo y verduras','tomate',1,'unidad',false),
('Wrap de pollo y verduras','lechuga',1,'unidad',false),
('Wrap de pollo y verduras','zanahoria',1,'unidad',false),
('Ensalada de garbanzos','garbanzo',1,'taza',true),
('Ensalada de garbanzos','tomate',1,'unidad',true),
('Ensalada de garbanzos','pepino',1,'unidad',false),
('Ensalada de garbanzos','cebolla',1,'unidad',false),
('Omelette de espinaca','huevo',2,'unidad',true),
('Omelette de espinaca','espinaca',1,'taza',true),
('Omelette de espinaca','tomate',1,'unidad',false),
('Pasta primavera','pasta',200,'g',true),
('Pasta primavera','zanahoria',1,'unidad',false),
('Pasta primavera','brocoli',1,'unidad',false),
('Pasta primavera','tomate',1,'unidad',false),
('Arroz con lentejas','arroz',1,'taza',true),
('Arroz con lentejas','lenteja',1,'taza',true),
('Arroz con lentejas','cebolla',1,'unidad',false),
('Tacos de frijol y tomate','frijol',1,'taza',true),
('Tacos de frijol y tomate','tomate',1,'unidad',true),
('Tacos de frijol y tomate','cebolla',1,'unidad',false),
('Pollo con arroz y zanahoria','pollo',250,'g',true),
('Pollo con arroz y zanahoria','arroz',1,'taza',true),
('Pollo con arroz y zanahoria','zanahoria',1,'unidad',false),
('Pollo con arroz y zanahoria','cebolla',1,'unidad',false),
('Sopa de lentejas','lenteja',1,'taza',true),
('Sopa de lentejas','zanahoria',1,'unidad',false),
('Sopa de lentejas','cebolla',1,'unidad',false),
('Sopa de lentejas','tomate',1,'unidad',false),
('Ensalada de pasta fria','pasta',180,'g',true),
('Ensalada de pasta fria','tomate',1,'unidad',false),
('Ensalada de pasta fria','zanahoria',1,'unidad',false),
('Ensalada de pasta fria','atun',1,'lata',true),
('Calabacin salteado con arroz','arroz',1,'taza',true),
('Calabacin salteado con arroz','calabacin',1,'unidad',true),
('Calabacin salteado con arroz','cebolla',1,'unidad',false),
('Pescado al tomate','pescado',220,'g',true),
('Pescado al tomate','tomate',2,'unidad',true),
('Pescado al tomate','cebolla',1,'unidad',false),
('Crepes de verduras','huevo',2,'unidad',true),
('Crepes de verduras','leche',1,'taza',true),
('Crepes de verduras','zanahoria',1,'unidad',false),
('Crepes de verduras','brocoli',1,'unidad',false),
('Garbanzos al curry','garbanzo',1,'taza',true),
('Garbanzos al curry','arroz',1,'taza',false),
('Garbanzos al curry','cebolla',1,'unidad',false),
('Garbanzos al curry','tomate',1,'unidad',false),
('Bowl de atun y arroz','arroz',1,'taza',true),
('Bowl de atun y arroz','atun',1,'lata',true),
('Bowl de atun y arroz','tomate',1,'unidad',false),
('Bowl de atun y arroz','zanahoria',1,'unidad',false),
('Sopa minestrone simple','pasta',100,'g',true),
('Sopa minestrone simple','tomate',2,'unidad',true),
('Sopa minestrone simple','zanahoria',1,'unidad',false),
('Sopa minestrone simple','frijol',1,'taza',false),
('Avena salada con huevo','avena',1,'taza',true),
('Avena salada con huevo','huevo',1,'unidad',true),
('Avena salada con huevo','tomate',1,'unidad',false),
('Papas rellenas de verduras','papa',3,'unidad',true),
('Papas rellenas de verduras','brocoli',1,'unidad',false),
('Papas rellenas de verduras','zanahoria',1,'unidad',false),
('Papas rellenas de verduras','cebolla',1,'unidad',false),
('Arroz mediterraneo','arroz',1,'taza',true),
('Arroz mediterraneo','tomate',1,'unidad',true),
('Arroz mediterraneo','garbanzo',1,'taza',false),
('Arroz mediterraneo','pepino',1,'unidad',false),
('Pollo a la plancha con ensalada','pollo',220,'g',true),
('Pollo a la plancha con ensalada','tomate',1,'unidad',false),
('Pollo a la plancha con ensalada','lechuga',1,'unidad',false),
('Pollo a la plancha con ensalada','zanahoria',1,'unidad',false),
('Salteado de verduras con huevo','huevo',2,'unidad',true),
('Salteado de verduras con huevo','brocoli',1,'unidad',false),
('Salteado de verduras con huevo','zanahoria',1,'unidad',false),
('Salteado de verduras con huevo','cebolla',1,'unidad',false)
) AS v(receta_nombre, ingrediente, cantidad, unidad, obligatorio)
JOIN recetas r ON r.nombre = v.receta_nombre
ON CONFLICT(receta_id, ingrediente) DO NOTHING;
